# Generated by Django 6.0.6 on 2026-07-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Symptoms described by the patient')),
                ('ai_response', models.TextField(help_text="AI's suggested possible causes")),
                ('urgency_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('urgent', 'Urgent - See a doctor')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='patient.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'Chat histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
